name: 'my_sqlite_project' # Project name
version: '1.0.0'           # Project version
config-version: 2          # dbt configuration version

profile: 'my_sqlite_profile' # profile name in profiles.yml

model-paths: ["models"]      # directory for model files (.sql)
analysis-paths: ["analyses"] # directory for analysis SQL
test-paths: ["tests"]        # directory for test files
seed-paths: ["seeds"]        # directory for raw CSV data
macro-paths: ["macros"]      # directory for dbt macros
snapshot-paths: ["snapshots"] # directory for snapshot settings

target-path: "target"  # path for compiled files
clean-targets:         # directories to remove on 'dbt clean'
  - "target"
  - "dbt_packages"

models:                     # model-level configurations
  my_sqlite_project:
    materialized: view      # default materialization (view, table, incremental)